import type { InferInsertModel } from "drizzle-orm";
import { eq } from "drizzle-orm";
import { db } from "../db/client";
import { skills } from "../db/schema/index";
import { agentTaskQueue } from "../db/schema/tasks";
import { broadcastSkillSyncForWorkspace } from "./skill-sync";

interface ParsedSediment {
  name: string;
  description: string;
  body: string;
}

/**
 * Very small frontmatter parser. We only read `name` and `description`;
 * everything else is left in the body. Avoids pulling in gray-matter for
 * a 20-line need.
 */
export function parseSedimentSkill(raw: string): ParsedSediment {
  const fmRe = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/;
  const match = raw.match(fmRe);
  if (!match) return { name: "", description: "", body: raw };
  const [, fm, body] = match;
  let name = "";
  let description = "";
  for (const line of (fm ?? "").split("\n")) {
    const m = line.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/);
    if (!m) continue;
    const key = m[1]?.toLowerCase();
    const value = (m[2] ?? "").trim();
    if (key === "name") name = value;
    if (key === "description") description = value;
  }
  return { name, description, body: body ?? "" };
}

export interface SedimentSkillArgs {
  taskId: string;
  rawContent: string;
}

/**
 * Insert a sedimented skill from a completed task. The skill takes its
 * workspace + owner from the task row, lands as visibility = "workspace"
 * (the task creator's workspace), and records `config.sourceTaskId` so
 * the UI can show 'generated by agent in task X'. Returns the new
 * skill id, or null if the task doesn't exist or already has a skill.
 */
export async function sedimentSkillFromTask(args: SedimentSkillArgs): Promise<string | null> {
  const task = await db.query.agentTaskQueue.findFirst({
    where: eq(agentTaskQueue.id, args.taskId),
  });
  if (!task) return null;

  // Idempotency: if this task already produced a skill, no-op. We scan
  // skills in this workspace for config.sourceTaskId match.
  const existing = await db
    .select()
    .from(skills)
    .where(eq(skills.workspaceId, task.workspaceId));

  for (const s of existing) {
    const cfg = (s.config ?? {}) as Record<string, unknown>;
    if (cfg.sourceTaskId === args.taskId) return null;
  }

  const parsed = parseSedimentSkill(args.rawContent);
  const baseName =
    parsed.name.trim() ||
    (task.triggerSummary?.trim()
      ? `auto-${task.triggerSummary.trim().slice(0, 30)}`
      : `auto-${args.taskId.slice(0, 8)}`);

  // Suffix on collision within the same workspace (unique index is
  // (workspaceId, name)).
  let name = baseName;
  if (existing.some((s) => s.name === baseName)) {
    name = `${baseName}-${args.taskId.slice(0, 6)}`;
  }

  const insert: InferInsertModel<typeof skills> = {
    workspaceId: task.workspaceId,
    ownerId: null,
    name,
    description: parsed.description,
    content: parsed.body,
    config: { sourceTaskId: args.taskId },
    visibility: "workspace",
  };
  const [row] = await db.insert(skills).values(insert).returning({ id: skills.id });
  if (!row) return null;

  // Push the new SKILL.md to every agent's daemon in this workspace
  // immediately so idle daemons write the file to disk without waiting
  // for their next task dispatch. bundlesForAgent already unions
  // workspace-visibility skills, so each fan-out picks this up.
  // Best-effort: a hub-side delivery failure must not roll back the
  // insert — sediment durability > fan-out completeness.
  try {
    await broadcastSkillSyncForWorkspace(task.workspaceId);
  } catch (err) {
    console.warn("[sediment] broadcastSkillSyncForWorkspace failed:", (err as Error).message);
  }

  return row.id;
}
